site_name: JourneyMap Documentation
site_url: https://teamjm.github.io/journeymap-docs2/

repo_name: TeamJM/journeymap-docs2
repo_url: https://github.com/TeamJM/journeymap-docs2

nav:
  - Home: index.md
  - About:
      - Licensing: About/licensing.md
  - Client Docs:
      - Installing: Client Docs/installing.md
      - Basic Usage: Client Docs/basic-usage.md
      - Full-Screen Map: Client Docs/full-screen-map.md
      - Waypoints: Client Docs/waypoints.md
      - Settings: Client Docs/settings.md
      - Webmap: Client Docs/webmap.md
      - Data Files: Client Docs/data-files.md
  - Server Docs:
      - Current Version: Server Docs/current-version.md
      - Bukkit & Spigot: Server Docs/bukkit-and-spigot.md
      - Minecraft 1.11 and older: Server Docs/minecraft-1.11-and-older.md
  - Tools & Customisation:
      - Tools & Customisation: Tools and Customisation/tools-and-customisation.md
  - Development:
      - Development: Development/development.md

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.tilde

plugins:
  - glightbox
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
