site_name: JourneyMap Documentation
site_url: https://teamjm.github.io/journeymap-docs/
docs_dir: ../docs/

repo_name: TeamJM/journeymap-docs
repo_url: https://github.com/TeamJM/journeymap-docs

theme:
  name: material
  custom_dir: ../overrides
  features:
    - search.highlight
    - search.suggest
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra:
  version:
    provider: mike

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - def_list

plugins:
  - glightbox
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
  - mike:
      version_selector: true
  - search

nav:
  - Home: index.md
  - About:
      - Credits: About/credits.md
      - Licensing: About/licensing.md
      - Support: About/support.md
  - Client Docs:
      - Installing: Client Docs/installing.md
      - Basic Usage: Client Docs/basic-usage.md
      - Full-Screen Map: Client Docs/full-screen-map.md
      - Waypoints: Client Docs/waypoints.md
      - Settings:
          - Overview: Client Docs/settings/overview.md
          - Grid: Client Docs/settings/grid.md
          - Minimap: Client Docs/settings/minimap.md
          - Full-Screen Map: Client Docs/settings/full-screen-map.md
          - Webmap: Client Docs/settings/webmap.md
          - Waypoint: Client Docs/settings/waypoint.md
          - Waypoint Beacons: Client Docs/settings/waypoint-beacon.md
          - Advanced Options: Client Docs/settings/advanced.md
  - Server Docs:
      - Basic Usage: Server Docs/basic-usage.md
      - Installing: Server Docs/installing.md
  - Tools & Customisation:
      - Custom Mob Icons: Tools and Customisation/custom-mob-icons.md
      - Integrate your mod: Tools and Customisation/integration.md
      - JourneyMap Tools: Tools and Customisation/journeymap-tools.md
      - Map a multiplayer server: Tools and Customisation/multiplayer-server.md
      - Topographic: Tools and Customisation/topographic.md
      - UI Themes: Tools and Customisation/ui-themes.md
  - Contributing:
      - Translate the mod: Contributing/translate-mod.md
      - Translate the docs: Contributing/translate-docs.md