name: Deploy the Docs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material
      - run: pip install mkdocs-glightbox
      - run: pip install mike
      - run: mkdocs gh-deploy --force -f ./config/en/mkdocs.yml
      - run: mike deploy --push --update-aliases 5.7.1 latest -F ./config/en/mkdocs.yml --rebase
      - run: mike set-default --push latest
